- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
  - vsphere_guest:
      vcenter_hostname: ukrdvmgvc001.dbpoc.uk
#      username: dbpoc\isibor
#      password: Integration12
      validate_certs: no
      guest: testansible
      state: powered_on
      vm_disk:
        disk1:
        size_gb: 20
        type: thin
        datastore: ukrd_esx_mgmt_data_001
      vm_nic:
        nic1:
        type: vmxnet3
        network: vm
        network_type: standard
      vm_hardware:
        memory_mb: 4024
        num_cpus: 2
        osid: ubuntu64Guest
        scsi: paravirtual
      esxi:
        datacenter: Reading-Dev
        hostname: ukrdsesxi001.dbpoc.uk

