---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the new vmware_guest module
- name: Create virtual machine
  hosts: all
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 'ukrdvmgvc001.dbpoc.uk'
    esxihost: 'ukrdsesxi001.dbpoc.uk'
    datacenter: 'Reading-Dev'
    datastore: 'ukrd_esx_mgmt_data_001'
    network: 'DMZ_Internet_Vlan201'
    vmtemplate: 'Template-Centos7'
    vmcluster: 'Reading-Dev-PoC'
    notes: 'Created by Ansible 01'
    dumpfacts: False
  tasks:
    - name: Check for required variables
      fail: msg="Must pass name and group to -e"
      when: name is not defined or group is not defined
      
    - name: Check for vSphere access parameters
      fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
      when: (vcenter_user is not defined) or (vcenter_pass is not defined)
        
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxihost }}"
        datacenter: "{{ datacenter }}"
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: 10
            type: thin
            datastore: "{{ datastore }}"
        nic:
          - type: vmxnet3
            network: "{{ network }}"
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: False
        state: present
      register: newvm
      
    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"

